spring:
    application:
        name: FITNESS-APP    
    datasource:
        url: jdbc:postgresql://localhost:5432/fitness-project
        username: postgres
        password: 0809
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect 

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

server:
    port: 8081




